apiVersion: apps/v1                          # Each API version defines a different set of 'objects' we can use 
kind: Deployment                             # Type of Object we're creating (i.e. StatefulSet, ReplicaController, Pod, Service)
metadata:                               
  name: redis-deployment                     # Name of the deployment
spec:
  replicas: 1                                # How many Pods to run
  selector:
    matchLabels:
      component: redis                       # Which template to use for these pods (Listed below)
  template:                                  # Configuration to be used by all PODS in this deployment
    metadata:
      labels:
         component: redis                    # Label of pod
    spec:
      containers:                            # List of container(s) to include on pod
        - name: redis                        # Human readable logging 
          image: redis                       # Using the public version not custom
          ports:
            - containerPort: 6379            # Works with a Service Object to exposes this port to the outside world
