apiVersion: v1                          # Each API version defines a different set of 'objects' we can use                   
kind: Service                           # Type of Object we're creating (i.e. StatefulSet, ReplicaController, Pod, Service)  
metadata:
  name: server-clusterip-service
spec:
  type: ClusterIP                       # Types of services: ClusterIP, NodePort, LoadBalancer, Ingress
  ports:                                # <port>:<targetPort>
    - port: 5000                        # Port that another POD/Container use to access client pod
      targetPort: 5000                  # Target port is the port inside the POD to open traffic 
  selector:
    component: server                   # Label selector system, associates the service with the Pods that have metadata > labels to this component