apiVersion: apps/v1                          # Each API version defines a different set of 'objects' we can use 
kind: Deployment                             # Type of Object we're creating (i.e. StatefulSet, ReplicaController, Pod, Service)
metadata:                               
  name: worker-deployment                    # Name of the deployment
spec:
  replicas: 1                                # How many Pods to run
  selector:
    matchLabels:
      component: worker                      # Which template to use for these pods (Listed below)
  template:                                  # Configuration to be used by all PODS in this deployment
    metadata:
      labels:
         component: worker                   # Label of pod
    spec:
      containers:                            # List of container(s) to include on pod
        - name: worker                       # Human readable logging 
          image: ryanwolfsr/multi-worker     # Name of the image on docker.hub to make this container from
          env:
            - name: REDIS_HOST
              value: redis-clusterip-service
            - name: REDIS_PORT
              value: '6379' 
