# Initial Base Image 
FROM node:alpine

# Specify work directory
WORKDIR '/app'

# List of dependencies to be installed
COPY ./package.json ./

# Install Dependencies
RUN npm install

# Copy remaining source files (Different because we don't want changes to code to require redownload of dependencies)
COPY . ./

# Startup command
CMD ["npm", "run", "dev"]